<?php

/**
 * @file
 * Provides a plant entity type.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\mbgna_plant\Entity\Plant;
use Drupal\user\UserInterface;
use Drupal\views\Views;

/**
 * Implements hook_theme().
 */
function mbgna_plant_theme() {
  return [
    'plant' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for plant templates.
 *
 * Default template: plant.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the plant information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_plant(array &$variables) {
  $plant = $variables['elements']['#plant'];
  if ($plant) {
    $variables['plant_id'] = $plant->id();
    $variables['url'] = $plant->toUrl('canonical')->toString();
    $variables['bundle'] = $plant->bundle();
    $variables['status'] = $plant->status->getString();
  }

  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function mbgna_plant_theme_suggestions_plant(array $variables) {
  $suggestions = [];
  $plant = $variables['elements']['#plant'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');
  $suggestions[] = 'plant__' . $sanitized_view_mode;
  $suggestions[] = 'plant__' . $plant->bundle();
  $suggestions[] = 'plant__' . $plant->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'plant__' . $plant->id();
  $suggestions[] = 'plant__' . $plant->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

/**
 * Implements hook_user_cancel().
 */
// function mbgna_plant_user_cancel($edit, UserInterface $account, $method) {
//   switch ($method) {
//     case 'user_cancel_block_unpublish':
//       // Unpublish plants.
//       $storage = \Drupal::entityTypeManager()->getStorage('plant');
//       $plant_ids = $storage->getQuery()
//         ->condition('uid', $account->id())
//         ->condition('status', 1)
//         ->execute();
//       foreach ($storage->loadMultiple($plant_ids) as $plant) {
//         $plant->set('status', FALSE);
//         $plant->save();
//       }
//       break;

//     case 'user_cancel_reassign':
//       // Anonymize plants.
//       $storage = \Drupal::entityTypeManager()->getStorage('plant');
//       $plant_ids = $storage->getQuery()
//         ->condition('uid', $account->id())
//         ->execute();
//       foreach ($storage->loadMultiple($plant_ids) as $plant) {
//         $plant->setOwnerId(0);
//         $plant->save();
//       }
//       break;
//   }
// }

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
// function mbgna_plant_user_predelete(UserInterface $account) {
//   // Delete plants.
//   $storage = \Drupal::entityTypeManager()->getStorage('plant');
//   $plant_ids = $storage->getQuery()
//     ->condition('uid', $account->id())
//     ->execute();
//   $plants = $storage->loadMultiple($plant_ids);
//   $storage->delete($plants);
//   // Delete old revisions.
//   $plant_ids = $storage->getQuery()
//     ->allRevisions()
//     ->condition('uid', $account->id())
//     ->execute();
//   foreach (array_keys($plant_ids) as $revision_id) {
//     $storage->deleteRevision($revision_id);
//   }
// }

/**
 * Implements hook_form_FORM_ID_alter()
 */
function mbgna_plant_form_views_exposed_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  $view = $form_state->getStorage('view');

  // Peonies
  if ($view['view']->id() == 'plant' && $view['view']->current_display == 'block_4') {
    $form['form']['#options']['All'] = t('Choose a form...');
    $form['season']['#options']['All'] = t('Choose a season...');
    $form['cultivar']['#options']['All'] = t('Choose a cultivar...');
    $form['country']['#options']['All'] = t('Choose an origin...');
  }

  // Bonsai
  if ($view['view']->id() == 'plant' && $view['view']->current_display == 'block_2') {
    $form['common_name']['#options']['All'] = t('Choose a common name...');
    $form['style']['#options']['All'] = t('Choose a style...');
    $form['genus']['#options']['All'] = t('Choose a genus...');
    $form['species']['#options']['All'] = t('Choose a species...');
  }
}